pipeline {
    agent any

    tools {
        maven 'maven' 
    }

    environment {
      BRANCH_NAME=env.GIT_BRANCH.replace("origin/", "")
    }

    stages {
        stage('checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/'+ BRANCH_NAME]], 
                    userRemoteConfigs: [[url: 'https://github.com/RajatADP/PACTron.git']])
            }
        }
        stage('Run Contract Tests') {
            steps {
                dir('customer_service') {
                    sh './mvnw verify'
                }
            }
        }
        stage('Publish Pact to Broker') {
            steps {
                dir('customer_service') {
//                     sh 'mvn pact:publish -Dpact.consumer.branch=${BRANCH_NAME} -Dpact.pacticipant.version=${GIT_COMMIT}'
                sh './mvnw pact:publish -Dpact.publish.consumer.version=$(git rev-parse HEAD) -Dpact.publish.consumer.branchName=$(git rev-parse --abbrev-ref HEAD)'
                }
            }
        }
        stage('Can-i-deploy?') {
            steps {
                //sh 'curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.91.0/pact-1.91.0-linux-x86_64.tar.gz'
                //sh 'tar xzf pact-1.91.0-linux-x86_64.tar.gz'
                //sh './mvnw pact:publish -Dpact.publish.consumer.version=$(git rev-parse HEAD) -Dpact.publish.consumer.branchName=$(git rev-parse --abbrev-ref HEAD)'
                    //dir('pact/bin') {
                        // sh './pact-broker create-webhook http://jenkins:8080/job/provider-ci/ --request POST -b http://pact-broker:9292 --contract_requiring_verification_published'
                        sh './mvnw pact:can-i-deploy -Dpacticipant=CustomerCatalogue -DpacticipantVersion=$(git rev-parse HEAD)'
                    //}
            }
        }
        /* stage('Tag pacticipant version to main') {
            input {
                message 'Consumer branch ${BRANCH_NAME} merged to main?'
            }
            steps {
                //dir('pact/bin') {
                    sh 'pact-broker create-version-tag -a CustomerCatalogue -e ${GIT_COMMIT} -b http://pact-broker:9292 -t main'
                    echo 'Safe to deploy to dev environment!'
                //}
            }
        } */
    }
}
